.TH CLI_TOOL 1 "August 2025" "cli_tool 1.0" "User Commands"
.SH NAME
cli_tool \- command-line utility for streamlined operations
.SH SYNOPSIS
.B cli_tool
[\fIOPTIONS\fR] [\fISUBCOMMAND\fR] [\fIARGS\fR...]
.SH DESCRIPTION
\fBcli_tool\fR is a flexible command-line tool designed to automate and streamline various tasks. It provides a suite of subcommands and options to enhance productivity and workflow efficiency for developers and system administrators.

.SH OPTIONS
.TP
.B \-h, \-\-help
Show help message and exit.
.TP
.B \-v, \-\-version
Display version information and exit.
.TP
.B \-c, \-\-config \fIFILE\fR
Specify a custom configuration file.
.TP
.B \-q, \-\-quiet
Suppress non-essential output.
.TP
.B \-d, \-\-debug
Enable debug output for troubleshooting.

.SH BUGS
Report bugs or issues via the GitHub repository at:
.br
https://github.com/Korneliusz93/cli_tool/issues

.SH AUTHOR
Developed by Korneliusz93.
.br
For contributions, refer to the GitHub repository.

.SH SEE ALSO
.BR git (1),
.BR bash (1),
.BR python (1)
.br
Additional documentation may be available at:
.br
https://github.com/Korneliusz93/cli_tool
